### ISSUE TITLE
Does this successfully detect IE11? 

### ISSUE THREAD

**Issue by carlosperez** [zenopopovici/Browser-Update#1]
Trying to use `vs: {i:11,f:31,o:21,s:6},` and IE 11 doesn't show the bar.

Yes, I'm working on a site that doesn't work with IE 11. :astonished:

**Comment by bboerendans** [comment]
Indeed. IE11 is detected as Chrome 39.
Tested in Windows 10 preview.

**Comment by zenopopovici** [comment]
New version supports current browsers.
