### ISSUE TITLE
Notification shows always on safari 5.1 even if 4 is configured

### ISSUE THREAD

**Issue by abimelex** [zenopopovici/Browser-Update#2]
I configured the script tho show just Safari version only below version 4, but the notification bar is always showed. How can I change this behaviour?

**Comment by zenopopovici** [comment]
I have no way to test this without an example.

**Comment by abimelex** [comment]
It seems to be related to those lines, when you set a browser below the "min-version" it will be reset to this...

    this.op.vsmin={i:8,f:5,o:12,s:5.1,n:12};
    var myvs=op.vs||{};
    this.op.vs =op.vs||this.op.vsdefault;
    for (b in this.op.vsakt) {
        if (this.op.vs[b]>=this.op.vsakt[b])
            this.op.vs[b]=this.op.vsakt[b]-0.2;
        if (!this.op.vs[b])
            this.op.vs[b]=this.op.vsdefault[b];
        if (this.op.vs[b]<this.op.vsmin[b])
            this.op.vs[b]=this.op.vsmin[b];      
    }

I set ´ vs: {i:7,f:10,o:6,s:4,c:10},´ so the safari 5.1 shouldn't show the "old-browser" hint, but it does so.

**Comment by zenopopovici** [comment]
Try modifying the vsmin values directly.
