### ISSUE TITLE
Minimum version settings do not match WhatBrowser.org

### ISSUE THREAD

**Issue by seadour** [zenopopovici/Browser-Update#3]
The warning message redirects users whose browser is out of date to WhatBrowser.org, but unfortunately that site has a much more lenient set of standards for which versions are out of date.

I tested it with Chrome and the site does not tell users to upgrade unless their version is 29 or less. Version 30 or higher is still considered "the most current version".

![screen shot 2015-04-28 at 3 42 20 pm](https://cloud.githubusercontent.com/assets/6138182/7381960/272780b2-edbe-11e4-8e2c-444754d5cc21.png)

I have not tested it in other browsers yet.

I e-mailed info@whatbrowser.org to see if they're aware of this. Hopefully they will update their standards.

In the meantime, you may want to modify your default back to Chrome <= 29 until Google updates whatbrowser.org, or point to a different website instead. It is confusing to users who get conflicting messages -- one from the script that says it is out of date, but another from the whatbrowser.org site that says it's "most current".

**Comment by zenopopovici** [comment]
It's a small issue, but I will not change the site. The whatbrowser.org is the only website that actually looks OK provides unbiased info and does not serve ads.
I've updated the defaults until someone from Google fixes it.

**Comment by seadour** [comment]
Thanks @zenopopovici. If I hear back from Google or notice they fix it, I will let you know right away.
